### ISSUE TITLE
Standardize on LED to Driver board male connector

### ISSUE THREAD

**Issue by plampkin** [uw-madison-chem-shops/wisconsin-photoreactor#11]
and take a photo of it to put into fabrication guide!

**Comment by untzag** [comment]
I'm thinking our official recommendation should be to just solder to the same breakable male headers we use for the fan. Heatshrink preferred if available. That way we have zero extra parts in the BOM.

**Comment by plampkin** [comment]
That's perfect! I'll take a photo of that setup tomorrow.
